### ISSUE TITLE
Spec should clarify that metrics are in seconds

### ISSUE THREAD

**Issue by dpogue** [WICG/server-timing#11]
There's current no units defined in the spec for how the `Server-Timing` metric will be interpreted.

**Comment by sroussey** [comment]
It is actually meant to be in `ms`, not `s`.

**Comment by igrigorik** [comment]
`duration` is defined as DOMHighResTimestamp. 

> A DOMHighResTimeStamp should represent a time in milliseconds accurate to 5 microseconds

**Comment by dpogue** [comment]
Okay, I'll file a Chrome DevTools bug then. It seems to be expecting the results in seconds.
Thanks
