### ISSUE TITLE
Allow user to get timing information for when a metric was received

### ISSUE THREAD

**Issue by bmaurer** [WICG/server-timing#4]
Many developers progressively render their page. For example, imagine a search engine -- the search engine might be implemented like this:

```
query = params['q'];
echo("<img src='logo.png' /><h1>Results for" + query + "</h1>);
res = executeSearch(query) 
echo(displayResults(res));
```

This creates a difficult problem for measurement tools. the responseStart value from user timing tells you when the browser received the first byte of the body. But when did the user receive the results?

A developer might do something like this:

```
start = now();
query = params['q'];
echo("<img src='logo.png' /><h1>Results for" + query + "</h1>);
header("Server-timing", "first-response=" + now() - start);
res = executeSearch(query) 
echo(displayResults(res));
header("Server-timing", "results=" + now() - start);
```

This would give them a metric of how long it took to generate first-response and results. But it tells you nothing about how long it took those bytes to get to the client. One could imagine adding a <script> tag create a performance mark at each point. However, if the browser's main thread is occupied, or the parsing of the document is blocked (say by a stylesheet) this will not reflect when the bytes were received.

This could be solved by adding a receivedTime attribute to PerformanceServerTiming. receivedTime would be defined as a DOMHighResTimeStamp that reflects the earliest time within the browser that the server timing header was parsed.

**Comment by sroussey** [comment]
I think you got cut off.

**Comment by bmaurer** [comment]
weird, i don't know why it cut me off.

Basically my suggestion here was to add a field to the server timing entry that tells you exactly when the header was received on the client -- in particular in http2 where you can intersperse headers at any point in the response

**Comment by igrigorik** [comment]
> This could be solved by adding a receivedTime attribute to PerformanceServerTiming. receivedTime would be defined as a DOMHighResTimeStamp that reflects the earliest time within the browser that the server timing header was parsed.

The right place to solve this is in Element Timing API - see https://github.com/w3c/charter-webperf/issues/30. We talked at TPAC about exposing parsed vs added-to-DOM vs painted timestamps. Let's continue there..
