### ISSUE TITLE
Metric values are timestamps in PerformanceServerTiming interface

### ISSUE THREAD

**Issue by bripkens** [WICG/server-timing#7]
Is it intended that all metric values have to be timestamps? I am confused right now about the scope of this specification as the header is described as defining generic metric key/value pairs. The `PerformanceServerTiming` interface, on the other hand, is limiting values to explicitly be `DOMHighResTimeStamp`s (which basically means `double`s, which should be fine).  Additionally, the field is called [duration](http://wicg.github.io/server-timing/#widl-ServerEntry-duration).

I'd expect the `duration` field to be called `value` and for it to be typed `double` to make it clearer that this is about any type of metric.

**Comment by igrigorik** [comment]
PerformanceServerTiming inherits from [PerformanceEntry](https://w3c.github.io/performance-timeline/#the-performanceentry-interface), which is the base for all the metrics we expose via PerformanceTimeline. So, yes, it has to be a DOMHighResTimestamp. 

That said, you don't have to provide the duration and can focus on name+description. See example here: http://wicg.github.io/server-timing/#examples

**Comment by bripkens** [comment]
Okay, so it is called `duration` for compatibility reasons. Thanks for explaining @igrigorik!
